project:
  type: website
  preview:
    port: 3434
    browser: true
    watch-inputs: true
    timeout: 3600

execute:
  freeze: auto

website:
  title: "Steven Ponce"
  description: "R code and Data Viz Projects"
  site-url: https://stevenponce.com
  repo-url: https://github.com/poncest/personal-website
  repo-actions:
    - source
    - issue
  favicon: assets/img/favicon.png
  twitter-card: true
  open-graph: true
  
  navbar:
    title: false
    pinned: true
    background: dark
    foreground: light
    left: 
      - text: "About"
        file: index.qmd
      - text: "Data Viz Projects"
        file: data_viz_projects.qmd
      - text: "Blog"
        file: blog.qmd
    right:
      - icon: github
        href: https://github.com/poncest
      - icon: linkedin
        href: https://www.linkedin.com/in/stevenponce/
      - icon: twitter
        href: https://twitter.com/sponce1
      - icon: mastodon
        href: https://graphics.social/@sponce1
      - icon: envelope
        text: Email
        href: mailto:steven_ponce@yahoo.com
  
  page-footer: 
    left: Copyright 2023, Steven Ponce
    right: This website is built with {{< fa heart title="a heart" >}}, [{{< fa brands github title="GitHub octocat logo" >}}](https://github.com/poncest/personal-website){target=_blank}, [{{< fa brands r-project title="R Project" >}}](https://www.r-project.org/about.html){target=_blank} and [Quarto](https://quarto.org/){target=_blank}

format:
  html:
    page-layout: full
    sidebar: false
    theme: [flatly, assets/styling/custom_theme.scss]
    mainfont: Nunito
    toc: true