project:
  type: website
  output-dir: _site    
  resources:
    - "google0e9f05038708b3a4.html"  
  preview:
    port: 3434
    browser: true
    watch-inputs: true
    timeout: 3600

execute:
  freeze: auto                

website:
  title: "Steven Ponce"
  description: "Data Visualizations and R Code"
  image: "assets/img/SP_avatar.png"     
  site-url: https://stevenponce.netlify.app/
  site-path: "/" 
  favicon: assets/img/SP_avatar.png  
  open-graph: true
  google-analytics: G-SG5QD2EXYM 
  twitter-card:                     
    creator: "@sponce1"
    card-style: summary_large_image
  search: true 
  repo-url: https://github.com/poncest/personal-website
  repo-branch: master   
  repo-subdir: data_visualizations
  back-to-top-navigation: true
  page-navigation: true

  navbar:
    title: false
    pinned: true
    background: dark
    foreground: light
    
    left: 
      - text: "Steven Ponce"
        href: https://stevenponce.netlify.app/
      - text: "About"
        file: index.qmd
      - text: "Data Visualizations"
        file: data_visualizations.qmd
      - text: "Projects"
        href: projects.qmd
    
    right:
      - icon: github
        href: https://github.com/poncest
      - icon: linkedin
        href: https://www.linkedin.com/in/stevenponce/
      - icon: twitter-x
        href: https://twitter.com/sponce1
      - text: "{{< iconify fa6-brands bluesky size=1.1em title='Bluesky' >}}"
        href: https://bsky.app/profile/sponce1.bsky.social
      - icon: envelope
        text: Email
        href: mailto:steven_ponce@yahoo.com
      - text: ""
        file: _components/theme-toggle.qmd

  page-footer:
      background: $navbar-bg 
      foreground: light
      left: "&#169; 2024 Steven Ponce"
      center: |
        <a class="link-dark me-1" href="https://github.com/poncest" title="github" target="_blank" rel="noopener">{{< fa brands github >}}</a>
        <a class="link-dark me-1" href="https://www.linkedin.com/in/stevenponce/" title="LinkedIn" target="_blank" rel="noopener">{{< fa brands linkedin >}}</a>
        <a class="link-dark me-1" href="https://twitter.com/sponce1" title="X/Twitter" target="_blank" rel="noopener">{{< fa brands x-twitter >}}</a>
        <a class="link-dark me-1" href="https://bsky.app/profile/sponce1.bsky.social" title="Bluesky" target="_blank" rel="noopener">{{< iconify fa6-brands bluesky >}}</a>
      right: |
        <a class="link-dark me-1" href="https://github.com/poncest/personal-website">{{< fa code >}} Source</a>
        <a class="link-dark me-1" href="https://github.com/poncest/personal-website/issues">{{< fa bug >}} Issues</a>

format:
  html:
    page-layout: full
    sidebar: false
    theme: 
      light: [flatly, assets/styling/custom_styles.scss]
      dark: [darkly, assets/styling/custom_styles_dark.scss]
    mainfont: "Roboto Mono"
    toc: true
    include-in-header:
      - text: |
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
          <script>
            const savedTheme = localStorage.getItem('theme') || 'light';
            document.documentElement.setAttribute('data-theme', savedTheme);
          </script>