project:
  type: website
  preview:
    port: 3434
    browser: true
    watch-inputs: true
    timeout: 3600

execute:
  freeze: auto                # re-render only when source changes

website:
  title: "Steven Ponce"
  description: "Data Visualizations and R Code"
  site-url: https://stevenponce.netlify.app/
  repo-url: https://github.com/poncest/personal-website
  repo-branch: master   
  repo-subdir: data_visualizations
  repo-actions:
    - source
    - issue
  favicon: assets/img/SP_avatar.png  
  open-graph: true
  back-to-top-navigation: true
  search: true
  page-navigation: true

  navbar:
    title: false
    pinned: true
    background: dark
    foreground: light
    left: 
      - text: "About"
        file: index.qmd
      - text: "Data Visualizations"
        file: data_visualizations.qmd
      - text: "Blog"
        file: blog.qmd
    right:
      - icon: github
        href: https://github.com/poncest
      - icon: linkedin
        href: https://www.linkedin.com/in/stevenponce/
      - icon: twitter-x
        href: https://twitter.com/sponce1
      # - icon: bluesky
      #   href: https://bsky.app/profile/sponce1.bsky.social
      - icon: envelope
        text: Email
        href: mailto:steven_ponce@yahoo.com
  
  page-footer: 
    left: "&#169; Copyright 2024"
    border: true
    center: |
      <a class="link-dark me-1" href="https://github.com/poncest" title="github" target="_blank" rel="noopener">{{< fa brands github >}}</a>
      <a class="link-dark me-1" href="https://x.com/sponce1" title="twitter" target="_blank" rel="noopener">{{< fa brands x-twitter >}}</a>
      <a class="link-dark me-1" href="https://www.linkedin.com/in/stevenponce/" title="LinkedIn" target="_blank" rel="noopener">{{< fa brands linkedin >}}</a>
      <a class="link-dark me-1" href="https://bsky.app/profile/sponce1.bsky.social" title="Bluesky" target="_blank" rel="noopener">{{< fa brands bluesky >}}</a>
    right: "Steven Ponce"
    
  twitter-card: 
    creator: "@sponce1"

format:
  html:
    page-layout: full
    sidebar: false
    theme: [flatly, assets/styling/custom_theme.scss]
    mainfont: Roboto
    toc: true

  