name: Render and Publish
on:
  push:
    branches: main
  pull_request:
    branches: main
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        
      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.0'
          
      - name: Install R Dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages:
            - any::rmarkdown
            - any::tidyverse
            # Add other packages your site needs
            
      - name: Render Quarto Project
        run: |
          mkdir -p _site
          quarto render
          
      # Add debugging steps
      - name: Check if _site exists
        run: |
          ls -la
          echo "Does _site exist?"
          if [ -d "_site" ]; then echo "Yes"; else echo "No"; fi
          echo "Contents of _site directory (if it exists):"
          if [ -d "_site" ]; then ls -la _site; else echo "_site directory does not exist"; fi
          
      # Replace the previous Deploy to Netlify step with these steps:
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          
      - name: Install Netlify CLI
        run: npm install -g netlify-cli
          
      - name: Deploy to Netlify
        run: netlify deploy --dir=_site --prod
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}